site_name: Documentation Laravel
site_description: Documentation for Laravel PHP framework in French.

nav:
  - Installation et configuration: index.md
  
theme:
  name: material
  language: fr
  custom_dir: overrides

extra:
  # Add custom meta tags if needed
  meta:
    keywords: Laravel, PHP, Documentation, Français

  # Configure the search plugin
  search:
    lang: fr

  # Configure the language selector in the footer
  language:
    select: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
